blog/urls.py
#Nosotros hemos creado esta url para poder dividir las urls del proyecto en  cada App

#importamos el path
from django.urls import path
# importamos la funcion de el archivo views
from .views import render_post, post_detail



#para navegar a una de la publiaciones 
app_name = 'blog' #para referenciar a los post de urlpatterns

urlpatterns = [
    path('', render_post, name='post'),
    # url dinamica || todo depues de 8000/blog/... lo busque como id
    path('<int:post_id>', post_detail, name= 'post_detail')
]

djangoPortafolio/urls.py
from django.contrib import admin
from django.urls import path
#importar include para que pueda leer las carpetas y decidir que sera importado
from django.urls import include


# Para las imagenes 
from django.conf.urls.static import static
from django.conf import settings

# Para las vistas 
from portfolio import views

#traer info de post 
from blog import urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    #al visitar la pagina blog que traiga lo que hay alli 
    path('blog/', include('blog.urls'))

    
]

    # Para imagenes 
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

blog/models.py
from django.db import models

#para el uso de datetime , fecha y hora
import datetime

# Create your models here.


# voy a usar una nueva forma sin necesidad de importar los modulos
# Definimos el modelo
class Post(models.Model):
    titulo = models.CharField(max_length=100)
    descipcion = models.TextField()
    # Que cree una nueva carpeta llamada blog y dentro  otra images
    # Dentro de images entaran las imagenes  
    imagen = models.ImageField( upload_to='blog/images')
    # si no se pone pues que ponga la fecha actual 
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
# modulo para el texto
from django.db.models.fields import CharField, URLField
# modulo para el manejo de las imagenes 
from django.db.models.fields.files import ImageField





# Create your models here.

# guardar informacion en la base de datos 

class Proyect (models.Model):
    titulo = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    #Luego crea una carpeta con { upload_to='portfolio/images/' }
    imagen = ImageField(upload_to='portfolio/images/') 
    #tengo que poner el model al principio y si quiero el los de arriab tambien
    url= models.URLField(blank=True) 

blog/views.py
from django.shortcuts import render
from .models import Post
# para consultar la base de datos usamos 
from django.shortcuts import get_object_or_404

# Create your views here.

#Creamos la primera vista de la url dentro de este archivo

def render_post(request):
    #Hacer una consulta si no todo esta bien
    posts = Post.objects.all()
    #Renderizar el archivo post.html
    return render (request, 'post.html', {'posts':posts})

# url dinamica || todo depues de 8000/blog/... lo busque como id
# Vista para rederizar los datos buscados

def post_detail(request, post_id):
    #que devuelva 404 si no existe lo que se busca 
    post = get_object_or_404(Post, pk = post_id )
    return render(request, 'post_detail.html', {'post':post})

portfolio/views.py
from django.shortcuts import render
#Para traer la informacion de los archivos 

from .models import Proyect






# Create your views here.

def home(request):
    projects = Proyect.objects.all()
            # {'projects':projects} ==> Para traer y mostras los proyectos
    return render(request , 'home.html', {'projects':projects} ) 

blog/templates/post.html
{% extends "layout.html" %}

{% block content %}



<h1 clase='fs-2' > Post </h1>

{% comment %} <pre>{{posts}} </pre> {% endcomment %}

{% comment %} Desde la clase de models.py  {% endcomment %}
{% for post in posts %}

<div class='p-3'>

    <div class="card card-body bg-black">

        <div class="row">

            <div class="col-3">
                <img class='img-fluid' src = '{{post.imagen.url}}' alt = '{{post.titulo}}'/>
            </div>

            <div class="col-9">

                <h2> {{post.titulo}}  </h2>
                {% comment %} descipcion {% endcomment %}
                {% comment %} decir que solo me muestre 100 caracteres : truncatechars:100 {% endcomment %}
                {% comment %} decir que intreprete el html que he puesto en la descripcion : stringtags  {% endcomment %}
                <p>  {{post.descipcion | striptags | truncatechars:100}} </p>
                {% comment %} Fecha formateada {% endcomment %}
                <h3> {{post.date | date:'M d Y' | upper}}</h3>
                {% comment %} #para navegar a una de la publiaciones  {% endcomment %}
                
            </div>
            
        </div>
        <a class='btn btn-primary' href = '{% url 'blog:post_detail' post.id %}'> {{post.titulo}} <a>
        
    </div>
    
</div>

    
{% endfor %}{% endblock content %}

blog/templates/post_detail.html
{% extends "layout.html" %}

{% block content %}

<div class="text-center">

    {% comment %} <!-- <h1>post detail CON el date </h1> --> {% endcomment %}
    {% comment %} Para probar si funciona {% endcomment %}



    <h2> {{post.titulo}} </h2>

    <h3 class='my-2 h5 text-muted'> {{post.date|date:'F jS Y'}} </h3>

    <img class='img-fluid' src='{{post.imagen.url}}' alt='{{post.titulo}}'>

    <div class='my-4'>
        <p> {{post.descipcion | safe}} </p>

    </div>



</div>

{% endblock  %}

portfolio/templates/home.html
{% extends "layout.html" %}

{% block content  %}

{% comment %} Cargamos la carpeta static para descargar documentos {% endcomment %}
{% load static %}

<header class="row bg-black">

    <div class="col-md-4 my-auto">
        <img src='{% static "porfolio/foto_perfil.png" %}' alt="">
    </div>

    <div class="col-md-8 my-auto">
        <h1>I am <strong>Ela Lino</strong></h1>

        <h3>I am a Python FullStack Developer</h3>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat recusandae nihil perspiciatis dolorum
            possimus et dolore est eligendi illo sunt ipsum fugit ea beatae, fugiat nobis ut, sint architecto
            dignissimos ex excepturi ipsa numquam maiores nostrum! Adipisci quibusdam, sunt sapiente iure magni ratione
            temporibus? Dolores officiis rerum facilis incidunt quod sint eum reprehenderit vero, quos, porro eos
            repudiandae quam nulla sed quas! Aperiam nihil sed molestiae assumenda sit illo aut. Asperiores repellat
            laudantium ea nobis eius beatae, maiores eligendi commodi, vero eaque repudiandae vitae mollitia. Facilis
            sint rem expedita itaque explicabo nostrum saepe, dolorem sunt, veniam ab similique nisi nulla.
        </p>

        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'porfolio/cvPython.pdf' %}"
            target="_blank">Download CV</a>


    </div>
</header>

{% comment %}
<pre>{{projects}}</pre> {% endcomment %}

<div class='row my-4 text-center'>

    <h3>My project</h3>

    {% for project in projects %}

    <div class="col-md-4 p-4">

        <div class="card bg-black card-project">
            
            <div class='card-body'>

                <img src='{{project.imagen.url}}' alt='{{project.titulo}}' class='card-img-top'>

                <h2> {{project.titulo}}</h2>
                <p>{{project.descripcion}}</p>
                

                {% if project.url  %}

                <a href='{{project.url}}' class='btn btn-light' target='_blank'>{{project.url}}</a>

                {% endif %}

            </div>
        </div>
    </div> 
    {% endfor %}
</div>
{% endblock  %}

portfolio/templates/layout.html
{% comment %} Importamos primero la etiqueta (carpeta) STATIC  {% endcomment %}

{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %} Bootstrap {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    {% comment %} vinculamos el archivo estatico {% endcomment %}
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <title>Portafolio</title>
</head>
<body class="text-light">
    {% comment %} Es el layou o diseno princpal  {% endcomment %}

    {% include "partials/navbar.html" %}

    <div class="container p-4">
        {% block content %} 
        {% endblock  %}
    </div>

    
</body>
</html>

portfolio/templates/partials/navbar.html
{% comment %} Cargamos static para poder descargar el pdf {% endcomment %}

{% load static %}



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">RR</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static "porfolio/cvPython.pdf"%}" target='_blank'>Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>